# Generated by Django 4.2.4 on 2023-11-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nippo', '0004_nippomodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='nippomodel',
            name='public',
            field=models.BooleanField(default=False, verbose_name='公開する'),
        ),
    ]
